<?php


//all the info of an album (except the pictures that are generated by the searchImageAPI by giving it an approriate id)
$album_id = isset($_GET['album_id']) ? $_GET['album_id'] : null;

include 'connectToDB.php';


$sql = "SELECT * FROM albums WHERE album_id = ?";
$stmt = $conn->prepare($sql);
$album_info = array(); 

if ($stmt) {
    $stmt->bind_param("s", $album_id); 
    $stmt->execute();
    $result = $stmt->get_result();
    
    if ($result->num_rows > 0) {
        while ($row = $result->fetch_assoc()) {
            $album_info['album_id']=$row['album_id'];
            $album_info['album_name']=$row['album_name'];
            $album_info['album_description']=$row['album_description'];
            $album_info['album_creation_date']=$row['album_creation_date'];
            $album_info['owner_id']=$row['user_id'];
        }

        $response = [
            'success' => true,
            'album_info' => $album_info
        ];
    } else {
        $response = [
            'success' => false,
            'message' => 'no album found'
        ];
    }
    
    $stmt->close();
} else {
    $response = [
        'success' => false,
        'message' => 'sql error'
    ]; 
}

$conn->close();
header('Content-Type: application/json');
echo json_encode($response);

?>